name: Hexo Build and Deploy

on: 
  push:
    branches: [master]

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    env:
      CNAME_tw: blog-legacy.clam.tw
      CNAME_moe: blog-legacy.clam.moe
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          # Whether to checkout submodules: `true` to checkout submodules or `recursive` to
          # recursively checkout submodules.
          #
          # When the `ssh-key` input is not provided, SSH URLs beginning with
          # `git@github.com:` are converted to HTTPS.
          #
          # Default: false
          submodules: 'recursive'
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: TZ=Asia/Taipei npm run build
      - name: Destroy my SEO?
        run: cp -v robots.txt ./public/robots.txt
      - name: Change CNAME
        run: |
          echo "${CNAME_tw}" | tee ./public/CNAME
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.TOKEN_JULY_25 }}
          external_repository: sean0921/${{ env.CNAME_tw }}
          publish_branch: master
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
      - name: Change CNAME
        run: |
          echo "${CNAME_moe}" | tee ./public/CNAME
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.TOKEN_JULY_25 }}
          external_repository: sean0921/${{ env.CNAME_moe }}
          publish_branch: master
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
